---
title: "Untitled"
author: "Leticia Salazar"
date: "2023-05-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(DataExplorer)
library(hrbrthemes)
library(ggplot2)
library(gridExtra)
library(plotly)
```



```{r}
pcos9 <- read.csv("https://raw.githubusercontent.com/letisalba/Data-698/master/Data-Collection-and-Analysis/csv/PCOS-Data.csv")
head(pcos9)
```


```{r}
colnames(pcos9)
```


```{r}
# renaming columns for `pcos` data
pcos9 <- pcos9 %>% 
  rename("Patient" = "patient",
         "Reg. menstrual periods(Yes/No)" = "Do.You.get.menstural.periods.at.regular.intervals...YES.NO.",
         "Weight gain(Yes/No)" = "Are.you.gaining.weight.Rapidly...YES.NO.",
         "Excess hair(Yes/No)" = "Do.You.have.Excess.of.facial..or.Body.Hair....YES.NO.",
         "Dark patches(Yes/No)" = "Do.you.Have.patches.of.dark.areas.on.your.skin..Yes.No.",
         "Pimples(Yes/No)" = "Do.You.suffer.from.pimples...YES.NO.",
         "Depression and Anxiety(Yes/No)" = "Do.you.face.deppression.and.anxietyt...YES.NO.",
         "History of diabetics and hypertension(Yes/No)" = "Do.you.any.family.history.of.Diabetics.and.Hyper.Tension...YES.NO.",
         "Difficult maintaining body weight(Yes/No)" = "Are.you.finding.any.difficulty.in.maintaining.your.body.weight...YES.NO.",
         "Do you have oily skin(Yes/No)" = "Do.you.have.na.oily.skin...YES.NO.",
         "Are you lossing hair or thinning(Yes/No)" = "Are.you.lossing.lot.of.hair.or.has.it.became.thinner.in.its.strength...YES.NO.",
         "Where do you friequently eat" = "Where.do.you.Frequently.eat.",
         "Do you exercise regularly(Yes/No)" = "Do.you.exercise.reguarly.",
         "Sleep after" = "I.sleep.after.",
         "Wake up at" = "I.wake.up.at.",
         "Are you newly admitted to hostel?" = "Are.you.mentally.stressed.due.to.following.exercise...Are.you.newly.admitted.to.hostel...",
         "Do you have personal problems?" = "Are.you.mentally.stressed.due.to.following.exercise...Do.you.have.personal.problems..",
         "Peer pressure?" = "Are.you.mentally.stressed.due.to.following.exercise..peer.presure..",
         "Change in dietry habits?" = "Are.you.mentally.stressed.due.to.following.exercise..Change.in.dietry.habits...",
         "How often do you eat fast foods?" = "How.often.do.you.eat.fast.foods.",
         "Class label" = "Class.label")

pcos9
```


```{r}
pcos9[pcos9 == "y"] <- 1      # Replacing y by 1
pcos9[pcos9 == "n"] <- 0       # Replacing n by 0
pcos9 
```







